// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBru5dcgOCtbzC-ddJ1lPkm_nO6_eMqMUM',
    appId: '1:290395990152:web:133f9080f17c482a19573d',
    messagingSenderId: '290395990152',
    projectId: 'sudanese-community-in-kfupm',
    authDomain: 'sudanese-community-in-kfupm.firebaseapp.com',
    storageBucket: 'sudanese-community-in-kfupm.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz1xfJQS4DToEZ033btmSXwSWnBKyFfD8',
    appId: '1:290395990152:android:cc63ab28bcf87a5019573d',
    messagingSenderId: '290395990152',
    projectId: 'sudanese-community-in-kfupm',
    storageBucket: 'sudanese-community-in-kfupm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFGMWNR8ww0pHlt1IUcMLVaTozt-l-occ',
    appId: '1:290395990152:ios:565a32cb9d271fa119573d',
    messagingSenderId: '290395990152',
    projectId: 'sudanese-community-in-kfupm',
    storageBucket: 'sudanese-community-in-kfupm.appspot.com',
    iosBundleId: 'com.example.sudaneseCommunity',
  );
}
